enableGlobalCache: true

logFilters:
    - code: YN0076
      level: discard

nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'
